apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-deployment
  labels:
    app: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '1234'
    spec:
      containers:
      - name: minecraft-server
        image: openhack/minecraft-server:2.0
        env:
         - name: EULA
           value: "TRUE"
        ports:
        - containerPort: 25565
          name: default
        - containerPort: 25575
          name: rcon
      - name: minecraft-metrics
        image: msopenhack.azurecr.io/minecraft-metrics:v1
        ports:
        - containerPort: 1234
          name: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
spec:
  type: LoadBalancer
  ports:
    - port: 25565
      name: default
    - port: 25575
      name: rcon
  selector:
    app: minecraft-server

---
  apiVersion: v1
  kind: Service
  metadata:
    name: grafana
    namespace: monitoring
  spec:
    type: LoadBalancer
    ports:
      - port: 3000
        targetPort: 3000
    selector: 
      app: kube-prometheus-grafana

---
  apiVersion: v1
  kind: Service
  metadata:
    name: prometheus
    namespace: monitoring
  spec:
    type: LoadBalancer
    ports:
      - port: 9090
        targetPort: 9090
    selector: 
      app: prometheus

